server:
  port: 9610


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1125/eureka/


spring:
  application:
    name: getway-zuul
zuul:
  routes:
    service-a:
      path: /service-a/**
      url: http://localhost:8762/service-a

    service-b:
      path: /service-b/**
      url: http://localhost:8761/service-b


